M48
; DRILL file {KiCad (6.0.10)} date Thu Feb 16 14:22:30 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-16T14:22:30-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.375Y-3.325
X5.5Y-3.225
X5.5Y-3.65
X5.7428Y-3.4322
T2
X5.5Y-3.025
X5.7Y-3.025
T0
M30
